default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Q1p2m3g4
  host: localhost

development:
  <<: *default
  database: rb_expert_development
test:
  <<: *default
  database: rb_expert_test